services:
  - type: web
    name: asistencia-unsam
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main_fixed.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
